### ISSUE TITLE
Need to force tornado version under 5 in requirements.txt or change event loop code

### ISSUE THREAD

**Issue by bio-boris** [kbase/narrative#1266]
On a fresh install of the narrative repo, the requirements.txt has a tornado requirement for tornado > 4
However, the latest tornado, v5, doesn't have io_loop anymore in the init.
You get the following error when running narratives

`   TypeError: __init__() got an unexpected keyword argument 'io_loop'`

The workaround is to change the requirements.txt to a lower version of tornado, such as
tornado==4.5.2

Some discussion of this I found online:
https://github.com/bokeh/bokeh/issues/7308

```
Uncaught exception in /narrative/api/kernels/c2416ccc-02db-4467-8cc7-fe9871fc46b2/channels
    Traceback (most recent call last):
      File "/workspace/narrative/narrative/narr-venv/lib/python2.7/site-packages/tornado/websocket.py", line 498, in _run_callback
        result = callback(*args, **kwargs)
      File "workspace/narrative/narrative/narr-venv/jupyter_notebook/notebook/services/kernels/handlers.py", line 260, in open
        super(ZMQChannelsHandler, self).open()
      File "workspace/narrative/narrative/narr-venv/jupyter_notebook/notebook/base/zmqhandlers.py", line 176, in open
        self.send_ping, self.ping_interval, io_loop=loop,

```

**Comment by briehl** [comment]
Thanks for finding this, and for the PR!
